version: '3.4'
services:
  netbox: &netbox
    image: localhost/netbox:v3.4-2.5.3-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    #ports:
    #  - "8000:8080"
    environment:
      SKIP_SUPERUSER: "${SKIP_SUPERUSER-false}"
      SUPERUSER_API_TOKEN: "${SUPERUSER_API_TOKEN-0123456789abcdef0123456789abcdef01234567}"
      SUPERUSER_EMAIL: "${SUPERUSER_EMAIL-admin@example.com}"
      SUPERUSER_NAME: "${SUPERUSER_NAME-admin}"
      SUPERUSER_PASSWORD: "${SUPERUSER_PASSWORD-admin}"
      ENFORCE_GLOBAL_UNIQUE: true
      REMOTE_AUTH_ENABLED: 'true'
      REMOTE_AUTH_BACKEND: 'netbox.authentication.LDAPBackend'
      AUTH_LDAP_SERVER_URI: "${AUTH_LDAP_SERVER_URI}"
      AUTH_LDAP_BIND_AS_AUTHENTICATING_USER: "true"
      AUTH_LDAP_USER_DN_TEMPLATE: "${AUTH_LDAP_USER_DN_TEMPLATE}"
      LDAP_IGNORE_CERT_ERRORS: 'true'
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "${AUTH_LDAP_GROUP_SEARCH_BASEDN}"
      AUTH_LDAP_GROUP_SEARCH_FILTER: '(&(cn:dn:=groups))'
      AUTH_LDAP_MIRROR_GROUPS: 'true'
      REDIS_PASSWORD: "${REDIS_PASSWORD-H733Kdjndks81}"
      NETBOX_DELETE_LEGACY_DATA: 1
      LOGLEVEL: "DEBUG"
      DB_WAIT_DEBUG: 1
  netbox-worker:
    <<: *netbox
  netbox-housekeeping:
    <<: *netbox
  postgres:
    #ports:
    #  - 5432:5432
    volumes:
    - ./postgres_init.d:/docker-entrypoint-initdb.d:z,ro
