version: '3.4'
services:
  netbox:
    ports:
      - "8000:8080"
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: "0123456789abcdef0123456789abcdef01234567"
      SUPERUSER_EMAIL: "admin@example.com"
      SUPERUSER_NAME: "admin"
      SUPERUSER_PASSWORD: "admin"
      ENFORCE_GLOBAL_UNIQUE: true
  postgres:
    ports:
      - 5432:5432
    volumes:
    - ./postgres_init.d:/docker-entrypoint-initdb.d:z,ro
