version: '3.4'
services:
  netbox:
    image: netbox:v3.3.8-2.3.0-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    # If you want the Nginx unit status page visible from the
    # outside of the container add the following port mapping:
    # - "8001:8081"
    ports:
      - "127.0.0.1::8080"
    environment: &netbox_environment
      SKIP_SUPERUSER: "${SKIP_SUPERUSER-false}"
      SUPERUSER_API_TOKEN: "${SUPERUSER_API_TOKEN-0123456789abcdef0123456789abcdef01234567}"
      SUPERUSER_EMAIL: "${SUPERUSER_EMAIL-admin@example.com}"
      SUPERUSER_NAME: "${SUPERUSER_NAME-admin}"
      SUPERUSER_PASSWORD: "${SUPERUSER_PASSWORD-admin}"
      ENFORCE_GLOBAL_UNIQUE: true
      REMOTE_AUTH_ENABLED: 'true'
      REMOTE_AUTH_BACKEND: 'netbox.authentication.LDAPBackend'
      AUTH_LDAP_SERVER_URI: "${AUTH_LDAP_SERVER_URI}"
      AUTH_LDAP_BIND_AS_AUTHENTICATING_USER: "true"
      AUTH_LDAP_USER_DN_TEMPLATE: "${AUTH_LDAP_USER_DN_TEMPLATE}"
      LDAP_IGNORE_CERT_ERRORS: 'true'
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "${AUTH_LDAP_GROUP_SEARCH_BASEDN}"
      AUTH_LDAP_GROUP_SEARCH_FILTER: '(&(cn:dn:=groups))'
      AUTH_LDAP_MIRROR_GROUPS: 'true'
      REDIS_PASSWORD: "${REDIS_PASSWORD-H733Kdjndks81}"
      REDIS_CACHE_PASSWORD: "${REDIS_CACHE_PASSWORD-t4Ph722qJ5QHeQ1qfu36}"
      DB_PASSWORD: "${POSTGRES_PASSWORD-J5brHrAXFLQSif0K}"
      #LOGLEVEL: "DEBUG"
      #DB_WAIT_DEBUG: 1
    labels:
      traefik.enable: "${TRAEFIK_ENABLE-false}"
      local.migrate.build: "${COMPOSE_BUILD-0}"
  netbox-worker:
    image: netbox:v3.3.8-2.3.0-plugins
    environment:
      <<: *netbox_environment
  netbox-housekeeping:
    image: netbox:v3.3.8-2.3.0-plugins
    environment:
      <<: *netbox_environment
  postgres:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-J5brHrAXFLQSif0K}"
    volumes:
      - ./postgres_init.d:/docker-entrypoint-initdb.d:z,ro
  redis:
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD-H733Kdjndks81}"
  redis-cache:
    environment:
      REDIS_PASSWORD: "${REDIS_CACHE_PASSWORD-t4Ph722qJ5QHeQ1qfu36}"
  mariadb:
    image: mariadb:10.3
    expose:
      - "3306"
    ports:
      - "127.0.0.1::3306"
    command: [
      '--net_read_timeout=31536000',
      '--net_write_timeout=31536000',
      '--max_allowed_packet=1073741824',
      '--connect_timeout=1000'
    ]
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: racktables_db
      MARIADB_USER: ap_racktables
      MARIADB_PASSWORD: password
    volumes:
    - ./mariadb_init.d:/docker-entrypoint-initdb.d:z,ro
