version: '3.4'
services:
  netbox:
    image: netbox:v3.4-2.5.3-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    ports:
      - "8000:8080"
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: "0123456789abcdef0123456789abcdef01234567"
      SUPERUSER_EMAIL: "admin@example.com"
      SUPERUSER_NAME: "admin"
      SUPERUSER_PASSWORD: "admin"
      ENFORCE_GLOBAL_UNIQUE: true
  netbox-worker:
    image: netbox:v3.4-2.5.3-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-housekeeping:
    image: netbox:v3.4-2.5.3-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  postgres:
    ports:
      - 5432:5432
    volumes:
    - ./postgres_init.d:/docker-entrypoint-initdb.d:z,ro
