version: '3.4'
services:
  netbox:
    volumes: &volumes
    - ./configuration:/etc/netbox/config:ro
    - netbox-media-files:/opt/netbox/netbox/media:rw
  netbox-worker:
    volumes: *volumes
  netbox-housekeeping:
    volumes: *volumes
  postgres:
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data:rw
    - ./postgres_init.d:/docker-entrypoint-initdb.d:ro
  redis:
    volumes:
    - netbox-redis-data:/data:rw
  redis-cache:
    volumes:
    - netbox-redis-cache-data:/data:rw
  mariadb:
    volumes:
    - ./mariadb_init.d:/docker-entrypoint-initdb.d:ro
  
