version: '3.4'
services:
  netbox:
    # If you want the Nginx unit status page visible from the
    # outside of the container add the following port mapping:
    # - "8001:8081"
    environment: &netbox_environment
      SKIP_SUPERUSER: "${SKIP_SUPERUSER-false}"
      SUPERUSER_API_TOKEN: "${SUPERUSER_API_TOKEN-0123456789abcdef0123456789abcdef01234567}"
      SUPERUSER_EMAIL: "${SUPERUSER_EMAIL-admin@example.com}"
      SUPERUSER_NAME: "${SUPERUSER_NAME-admin}"
      SUPERUSER_PASSWORD: "${SUPERUSER_PASSWORD-admin}"
      ENFORCE_GLOBAL_UNIQUE: true
      REMOTE_AUTH_ENABLED: 'true'
      REMOTE_AUTH_BACKEND: 'netbox.authentication.LDAPBackend'
      AUTH_LDAP_SERVER_URI: "${AUTH_LDAP_SERVER_URI}"
      AUTH_LDAP_BIND_AS_AUTHENTICATING_USER: "true"
      AUTH_LDAP_USER_DN_TEMPLATE: "${AUTH_LDAP_USER_DN_TEMPLATE}"
      LDAP_IGNORE_CERT_ERRORS: 'true'
      AUTH_LDAP_GROUP_SEARCH_BASEDN: "${AUTH_LDAP_GROUP_SEARCH_BASEDN}"
      AUTH_LDAP_GROUP_SEARCH_FILTER: '(&(cn:dn:=groups))'
      AUTH_LDAP_MIRROR_GROUPS: 'true'
      REDIS_PASSWORD: "${REDIS_PASSWORD-H733Kdjndks81}"
      REDIS_CACHE_PASSWORD: "${REDIS_CACHE_PASSWORD-t4Ph722qJ5QHeQ1qfu36}"
      DB_PASSWORD: "${POSTGRES_PASSWORD-J5brHrAXFLQSif0K}"
      #LOGLEVEL: "DEBUG"
      #DB_WAIT_DEBUG: 1
  netbox-worker:
    environment:
      <<: *netbox_environment
  netbox-housekeeping:
    environment:
      <<: *netbox_environment
  postgres:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-J5brHrAXFLQSif0K}"
    volumes:
      - ./postgres_init.d:/docker-entrypoint-initdb.d:z,ro
  redis:
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD-H733Kdjndks81}"
  redis-cache:
    environment:
      REDIS_PASSWORD: "${REDIS_CACHE_PASSWORD-t4Ph722qJ5QHeQ1qfu36}"
