version: '3.4'
services:
  netbox:
    image: netbox:v3.5-2.6.1-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    ports:
      - "8000:8080"
    # If you want the Nginx unit status page visible from the
    # outside of the container add the following port mapping:
    # - "8001:8081"
    # healthcheck:
      # Time for which the health check can fail after the container is started.
      # This depends mostly on the performance of your database. On the first start,
      # when all tables need to be created the start_period should be higher than on
      # subsequent starts. For the first start after major version upgrades of NetBox
      # the start_period might also need to be set higher.
      # Default value in our docker-compose.yml is 60s
      # start_period: 90s
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: "0123456789abcdef0123456789abcdef01234567"
      SUPERUSER_EMAIL: "admin@example.com"
      SUPERUSER_NAME: "admin"
      SUPERUSER_PASSWORD: "admin"
      ENFORCE_GLOBAL_UNIQUE: true
  netbox-woker:
    image: netbox:v3.5-2.6.1-plugins
  netbox-housekeeping:
    image: netbox:v3.5-2.6.1-plugins
  postgres:
    ports:
      - 5432:5432
    volumes:
    - ./postgres_init.d:/docker-entrypoint-initdb.d:z,ro
